project:
  type: book
  output-dir: docs
  
execute: 
  echo: false
  warning: false
  message: false

knitr:
  opts_chunk:
    out.width: "100%"
    out.height: "100%"
  
book:
  title: "Equity in Vaccine Access in Ho Chi Minh City"
  chapters:
    - index.qmd
    - vac_cov.qmd
    - ipsum.qmd
    
    
format:
  html:
    theme: cosmo
    code-copy: true
    fig-format: svg
  pdf:
    documentclass: scrreprt

editor: visual    
    